# Generated by Django 3.2 on 2023-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
